#!/bin/sh
#
# Automatically update cross-version squid.conf documentation
# based on files generated by mk-www-manuals.sh
#

# Known Bug:
#  Does not remove references to directives dropped. This is
#  an issue for branch 'master' directive erasure.

webpath=`cat ~/.website-path`
cd ${webpath}/content/Doc/config

# Ignore v1 since it does not publish this type of documentation
# Ignore v2 since it is no longer changing
# Ignore v3 since it is no longer changing

# Dynamically detect which v4+ releases exist right now and grok them all.
VERS4=`ls -1t ${webpath}/content/Versions/ | grep -v "CVS|sig.dyn"`
for v in ${VERS4} "$@" ; do
#	echo "FOUND: $v"
	if test -d ${webpath}/content/Versions/${v}/cfgman ; then
#	echo "SCAN: ${v}/cfgman"
	for directive in ${webpath}/content/Versions/${v}/cfgman/*.html; do
		directive=`basename $directive .html`
		case $directive in
		index|index_all|"*")
			:
			;;
		*)
			if [ ! -d $directive ]; then
				echo "Updating $v docs for $directive"
				mkdir $directive
				ln -s ../template.dyn $directive/index.dyn
			else
				touch -c $directive/index.dyn
			fi
			;;
		esac
	done
	fi
done
